apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw3.fullname" . }}
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
  selector:
    {{- include "hw3.selectorLabels" . | nindent 4 }}
