apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw2-app
  template:
    metadata:
      labels:
        app: hw2-app
    spec:
      containers:
        - name: hw2
          imagePullPolicy: Always
          image: nik1202/hw1:v2
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hw2-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: hw2-secret
                  key: DB_PASS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: hw2-config
                  key: DB_URL
          ports:
            - name: web
              containerPort: 8000
