replicaCount: 2

image:
  repository: nik1202/hw1:v3

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/"]
